# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    # Puppet master on Centos 7
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end

    puppet.vm.synced_folder ".", "/vagrant"
    puppet.vm.synced_folder "../code", "/puppet_code"
    puppet.vm.synced_folder "../puppetserver", "/puppet_puppetserver"
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "puppet.example.com"
    puppet.vm.network :private_network, ip:  "10.0.20.10"
    puppet.hostmanager.aliases = "%w(puppet)"
    puppet.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppetserver -y
      sudo rm -rf /etc/puppetlabs/code
      sudo ln -s /puppet_code /etc/puppetlabs/code
      sudo rm -rf /etc/puppetlabs/puppetserver
      sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
      # change jvm heapsize
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
      # Don't do this in production mode!
      echo "*.example.com" >> sudo tee /etc/puppetlabs/puppet/autosign.conf
      sudo systemctl start puppetserver
    SHELL
  end

  config.vm.define "agent1" do |agent1|
    # Puppet agent on Centos 7
    agent1.vm.box = "centos/7"
    agent1.vm.hostname = "agent1.example.com"
    agent1.vm.network :private_network, ip:  "10.0.20.20"
    agent1.hostmanager.aliases = "%w(agent1)"
  end

  config.vm.define "agent2" do |agent2|
    # Puppet agent on Debian based
    agent2.vm.box = "ubuntu/trusty64"
    agent2.vm.hostname = "agent2.example.com"
    agent2.vm.network :private_network, ip:  "10.0.20.21"
    agent2.hostmanager.aliases = "%w(agent2)"
  end


end
